import { DataTypes } from "sequelize";
import sequelize from "../config/database.js";

const Budget = sequelize.define(
  "Budget",
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },

    userId: {
      type: DataTypes.UUID,
      allowNull: false,
      field: "user_id",
      references: {
        model: "users",
        key: "id",
        onDelete: "CASCADE",
      },
    },

    categoryId: {
      type: DataTypes.UUID,
      allowNull: true,
      field: "category_id",
      references: {
        model: "categories",
        key: "id",
        onDelete: "SET NULL",
      },
    },

    monthlyLimit: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      field: "monthly_limit",
    },

    period: {
      type: DataTypes.ENUM("monthly"),
      allowNull: false,
      defaultValue: "monthly",
    },

    isAutoGenerated: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true,
      field: "is_auto_generated",
    },

    explanation: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
  },
  {
    tableName: "budgets",
    timestamps: true,
    indexes: [
      {
        unique: true,
        fields: ["user_id", "category_id", "period"],
      },
    ],
  }
);

export default Budget;
