import { api } from "./axios";

export interface Budget {
    budgetId: string;
    category: string;
    monthlyLimit: number;
    spent: number;
    remaining: number;
    usagePercent: number;
    isAutoGenerated: boolean;
    explanation: string | null;
}

export interface BudgetsResponse {
    success: boolean;
    data: Budget[];
}

export interface GenerateBudgetsPayload {
    months?: number;
    bufferPercent?: number;
}

export const getBudgets = async (month?: string): Promise<Budget[]> => {
    const params = month ? { month } : {};
    const response = await api.get<BudgetsResponse>("/budgets", { params });
    return response.data.data;
};

export const generateBudgets = async (payload?: GenerateBudgetsPayload): Promise<Budget[]> => {
    const response = await api.post<BudgetsResponse>("/budgets/generate", payload || {});
    return response.data.data;
};
